Version v1.0.6

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -1,70 +1,78 @@
-# Execute Pipeline when Pushing Tags
-
 name: CI/CD - Flask Docker
+
 on:
   push:
     tags:
       - "v*.*.*"
-      - "latest"
-      
+
+env:
+  IMAGE_NAME: talkeret/ci-cd-flask-app
+
 jobs:
-  ci: 
+  ci:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
         with:
-          fetch-depth: 0 # imprt all tags and commits
+          fetch-depth: 0
+
+      - name: Set Python
+        uses: actions/setup-python@v6
+        with:
+          python-version: 3.11
+
       - name: Install dependencies
         run: |
           pip install --upgrade pip
           pip install -r requirements.txt
+          pip install pytest
 
-      - name: Build Docker image
-        run: docker build -t ci-cd-flask-app:latest .
+      - name: Build Docker container for testing
+        run: docker build -t flask-test:ci .
 
-      - name: Run container
+      - name: Run container for tests
         run: |
-          docker run -d --name flask-app -p 5000:5000 ci-cd-flask-app:latest
+          docker run -d --name flask-app -p 5000:5000 flask-test:ci
           sleep 5
 
-      - name: Install & run pytests
+      - name: Run pytest + health check
         run: |
-          pip install pytest
           pytest
-
-      - name: Health check
-        run: |
-          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/health)
-          if [ "$response" -ne 200 ]; then
-            echo "Health check failed! HTTP code: $response"
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/health)
+          if [ "$RESPONSE" -ne 200 ]; then
+            echo "Health check failed! HTTP code: $RESPONSE"
             exit 1
-          else
-            echo "Health check passed ✅"
           fi
+
+      - name: Stop test container
+        run: docker rm -f flask-app || true
 
   cd:
     needs: ci
     runs-on: ubuntu-latest
     steps:
+      - name: Checkout repository
+        uses: actions/checkout@v5
+
       - name: Login to Docker Hub
-        uses: docker/login-action@v2
+        uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKER_HUB_USERNAME }}
           password: ${{ secrets.DOCKER_HUB_TOKEN }}
 
-      - name: Set version
+      - name: Set version from tag
         run: |
           VERSION=${GITHUB_REF#refs/tags/v}
           echo "VERSION=$VERSION" >> $GITHUB_ENV
 
-      - name: Tag & Push
+      - name: Build & Push Docker image
         run: |
-          docker tag ci-cd-flask-app:latest talkeret/ci-cd-flask-app:$VERSION
-          docker tag ci-cd-flask-app:latest talkeret/ci-cd-flask-app:latest
-          docker push talkeret/ci-cd-flask-app:$VERSION
-          docker push talkeret/ci-cd-flask-app:latest
+          docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest .
+          docker push $IMAGE_NAME:$VERSION
+          docker push $IMAGE_NAME:latest
 
-      - name: Stop container
+      - name: Deploy container
         run: |
-          docker rm -f flask-app  || true
+          docker rm -f flask-app || true
+          docker run -d --name flask-app -p 5000:5000 $IMAGE_NAME:$VERSION
