Version v1.0.5

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -1,78 +1,69 @@
-name: CI/CD - Flask Docker
-
 # Execute Pipeline when Pushing Tags
 
+name: CI/CD - Flask Docker
 on:
   push:
     tags:
       - "v*.*.*"
       
 jobs:
-  build-test-deploy:
+  ci: 
     runs-on: ubuntu-latest
-
     steps:
-    # Checkout code
-    - name: Checkout repository
-      uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0 # imprt all tags and commits
+      - name: Install dependencies
+        run: |
+          pip install --upgrade pip
+          pip install -r requirements.txt
 
-    # Install dependencies
-    - name: Install dependencies
-      run: |
-        pip install --upgrade pip
-        pip install -r requirements.txt
+      - name: Install & run pytests
+        run: |
+          pip install pytest
+          pytest
 
-    # Python
-    - name: Run pytests
-      run: |
-        pip install pytest
-        pytest
+      - name: Build Docker image
+        run: docker build -t ci-cd-flask-app:latest .
 
-    # Build Docker image
-    - name: Build Docker image
-      run: |
-        docker build -t ci-cd-flask-app:latest .
+      - name: Run container
+        run: |
+          docker run -d --name flask-app -p 5000:5000 ci-cd-flask-app:latest
+          sleep 5
 
-    # Run container
-    - name: Run container
-      run: |
-        docker run -d --name flask-app -p 5000:5000 ci-cd-flask-app:latest
-        sleep 5
+      - name: Health check
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/health)
+          if [ "$response" -ne 200 ]; then
+            echo "Health check failed! HTTP code: $response"
+            exit 1
+          else
+            echo "Health check passed ✅"
+          fi
 
-    # Health check
-    - name: Health check
-      run: |
-        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/health)
-        if [ "$response" -ne 200 ]; then
-          echo "Health check failed! HTTP code: $response"
-          exit 1
-        else
-          echo "Health check passed ✅"
-        fi
+  cd:
+    needs: ci
+    runs-on: ubuntu-latest
+    steps:
+      - name: Login to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_TOKEN }}
 
-    # Login to Docker Hub
-    - name: Login to Docker Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKER_HUB_USERNAME }}
-        password: ${{ secrets.DOCKER_HUB_TOKEN }}
+      - name: Set version
+        run: |
+          VERSION=${GITHUB_REF#refs/tags/v}
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
 
-    # Set Version
-    - name: Set version
-      run: |
-        VERSION=${GITHUB_REF#refs/tags/v}
-        echo "VERSION=$VERSION" >> $GITHUB_ENV
+      - name: Tag & Push
+        run: |
+          docker tag ci-cd-flask-app:latest talkeret/ci-cd-flask-app:$VERSION
+          docker tag ci-cd-flask-app:latest talkeret/ci-cd-flask-app:latest
+          docker push talkeret/ci-cd-flask-app:$VERSION
+          docker push talkeret/ci-cd-flask-app:latest
 
-    - name: Tag & Push
-      run: |
-        docker tag ci-cd-flask-app:latest talkeret/ci-cd-flask-app:$VERSION
-        docker tag ci-cd-flask-app:latest talkeret/ci-cd-flask-app:latest
-
-        docker push talkeret/ci-cd-flask-app:$VERSION
-        docker push talkeret/ci-cd-flask-app:latest
-
-
-    # Cleanup
-    - name: Stop container
-      run: |
-        docker rm -f flask-app  || true
+      - name: Stop container
+        run: |
+          docker rm -f flask-app  || true
